/*
===============================================================================

	retail-png.test.mjs

	Call of Duty 2 / id Tech PNG Encoder Unit Tests
	Validates byte-exact roundtrip compression, CRC32 chunk validation,
	and input buffer bounds checking for synthetic images.

===============================================================================
*/

import test from 'node:test';
import assert from 'node:assert/strict';
import { inflateSync } from 'node:zlib';

import { encodePNG, crc32 } from '../decoders/retail-png.ts';


// ---------------------------------------------------------------------------
// png decoding helper for verification
// ---------------------------------------------------------------------------

/*
====================
decode

Parses and decompresses raw PNG bytes using Node zlib to verify
that the output generated by encodePNG adheres to RFC 2083.
====================
*/
function decode( png ) {
	const view = new DataView( png.buffer, png.byteOffset, png.byteLength );
	let width = 0;
	let height = 0;
	const chunks = [];

	for ( let at = 8; at < png.length; ) {
		const length = view.getUint32( at );
		const type = new TextDecoder().decode( png.slice( at + 4, at + 8 ) );

		assert.equal( crc32( png.slice( at + 4, at + 8 + length ) ), view.getUint32( at + 8 + length ), type + ' CRC' );

		if ( type === 'IHDR' ) {
			width = view.getUint32( at + 8 );
			height = view.getUint32( at + 12 );
		}

		if ( type === 'IDAT' ) {
			chunks.push( png.slice( at + 8, at + 8 + length ) );
		}

		at += length + 12;
	}

	const raw = inflateSync( Buffer.concat( chunks ) );
	const stride = width * 4;
	const out = new Uint8Array( width * height * 4 );

	for ( let y = 0; y < height; y++ ) {
		const f = raw[y * ( stride + 1 )];
		assert.ok( [0, 1, 2].includes( f ) );

		for ( let x = 0; x < stride; x++ ) {
			const at = y * stride + x;
			const prevLeft = f === 1 && x >= 4 ? out[at - 4] : 0;
			const prevUp = f === 2 && y ? out[at - stride] : 0;

			out[at] = ( raw[y * ( stride + 1 ) + x + 1] + prevLeft + prevUp ) & 255;
		}
	}

	return out;
}


// ---------------------------------------------------------------------------
// test suites
// ---------------------------------------------------------------------------

for ( const kind of ['solid', 'gradient', 'noise', 'transparent-rgb'] ) {
	test( `PNG roundtrip is byte-exact for ${kind}`, async () => {
		const width = 67;
		const height = 49;
		const bytes = new Uint8Array( width * height * 4 );
		let random = 12345;

		for ( let i = 0; i < bytes.length; i++ ) {
			random ^= random << 13;
			random ^= random >>> 17;
			random ^= random << 5;

			bytes[i] = kind === 'solid'
				? 180
				: kind === 'gradient'
					? Math.floor( i / 4 ) % 256
					: random & 255;

			if ( kind === 'transparent-rgb' && i % 4 === 3 ) {
				bytes[i] = i % 12 === 3 ? 0 : 1;
			}
		}

		const before = bytes.slice();
		const encoded = await encodePNG( width, height, bytes );
		const decoded = decode( encoded );

		assert.deepEqual( decoded, before );
		assert.deepEqual( bytes, before, 'input is never mutated' );
	} );
}

test( 'PNG encoder rejects invalid sizes and incomplete RGBA buffers', async () => {
	await assert.rejects( encodePNG( 0, 1, new Uint8Array( 0 ) ), /Invalid PNG/ );
	await assert.rejects( encodePNG( 2, 2, new Uint8Array( 4 ) ), /Invalid PNG/ );
} );
